###
# releasewarrior-data paths
releases:
  upcoming:
    thunderbird: upcoming/thunderbird
  inflight:
    thunderbird: inflight/thunderbird
  archive:
    thunderbird: archive/thunderbird

postmortems: postmortems
###

###
# template paths
templates:
  # input
  data:
    thunderbird:
      beta: thunderbird/beta.json.tmpl
      release: thunderbird/release.json.tmpl
  # output
  wiki:
    generic: markdown/generic.md.tmpl
    postmortem: markdown/postmortem.md.tmpl
  corsica:
    index: corsica/index.template.html


### location of release cmd output artifacts
releasewarrior_artifacts:
  logs: logs

## corsica settings
corsica_enabled: true
corsica: index.html


## data repo
releasewarrior_data_repo: ~/.mozbuild/releasewarrior-data
upstream_repo_url_pattern: ((?:https|ssh)://|git@)github\.com[:/]mozilla-releng/releasewarrior-data(\.git)?
simplified_repo_url: github.com/mozilla-releng/releasewarrior-data # Used only to simplify what's logged out###
